import Head from 'next/head'
import About from '../components/About'
import Input from '../components/form/Input'
import Header from '../components/layout/Header'
import Home from './home'

export default function Index() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Home />
      <About />
      <div className="p-20 container mx-auto">
        <Input />
      </div>
    </div>
  )
}
