import Head from 'next/head'
import Home from './home'

export default function Index() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='text-center text-3xl'>Food Ordering App</h1>
      <Home />
    </div>
  )
}
